# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Noise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'AFDateHelper', :git => 'https://github.com/FroeMic/DateHelper.git'
    pod 'JustPeek', :git => 'https://github.com/FroeMic/JustPeek.git'
    pod 'lottie-ios'


  # Pods for Noise

  target 'NoiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
